// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2_gWs4ICOww_GJBaMJibvg34E0y61dY',
    appId: '1:337720785610:web:dc8a1a73be86cb9db95233',
    messagingSenderId: '337720785610',
    projectId: 'okey-4b8c0',
    authDomain: 'okey-4b8c0.firebaseapp.com',
    storageBucket: 'okey-4b8c0.firebasestorage.app',
    measurementId: 'G-R9J5D9L64G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySkhT70QtOaJHhqzKt_2z5I66SO9Q2Jg',
    appId: '1:337720785610:android:2816aac7f4414fb1b95233',
    messagingSenderId: '337720785610',
    projectId: 'okey-4b8c0',
    storageBucket: 'okey-4b8c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYCEf_wB1Pf9-5aNoVAinWs-mqCo3RAU',
    appId: '1:337720785610:ios:ee297a2d6c1b5e2ab95233',
    messagingSenderId: '337720785610',
    projectId: 'okey-4b8c0',
    storageBucket: 'okey-4b8c0.firebasestorage.app',
    iosBundleId: 'com.example.okey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYCEf_wB1Pf9-5aNoVAinWs-mqCo3RAU',
    appId: '1:337720785610:ios:ee297a2d6c1b5e2ab95233',
    messagingSenderId: '337720785610',
    projectId: 'okey-4b8c0',
    storageBucket: 'okey-4b8c0.firebasestorage.app',
    iosBundleId: 'com.example.okey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2_gWs4ICOww_GJBaMJibvg34E0y61dY',
    appId: '1:337720785610:web:bf9db5980691b786b95233',
    messagingSenderId: '337720785610',
    projectId: 'okey-4b8c0',
    authDomain: 'okey-4b8c0.firebaseapp.com',
    storageBucket: 'okey-4b8c0.firebasestorage.app',
    measurementId: 'G-29X5PH46G1',
  );
}
